name: 'nyc_analytics'
version: '1.0.0'
config-version: 2
# Some default settings for dbt
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
 - "target"
 - "dbt_packages"

# Set up models, which are basically SQL files, to create tables
models:
 nyc_analytics:
   +materialized: table

   assignment_work:
     staging:
       +materialized: table
       +schema: cis_9440_group_project_staging # Dataset name for the staging for project

     marts:
       +materialized: table
       +schema: cis_9440_group_project_warehouse_marts # Dataset name for the warehouse marts for data project
      
       shared:
         +materialized: table

       motor_veh_collision:
         +materialized: table

       street_complaints_311:
         +materialized: table
